export interface Question {
    id: number;
    text: string;
}

export const speakingPart1Questions: Question[] = [
    { id: 1, text: "Please tell me about your family." },
    { id: 2, text: "Tell me about the place you live in." },
    { id: 3, text: "Tell me about your hometown" },
    { id: 4, text: "Describe your home." },
    { id: 5, text: "What is your favorite season? Why?" },
    { id: 6, text: "What is the weather like today?" },
    { id: 7, text: "How do you relax in the evening?" },
    { id: 8, text: "What do you like doing in your free time?" },
    { id: 9, text: "What do you do at the weekend?" },
    { id: 10, text: "What is your favorite music?" },
    { id: 11, text: "Describe a member in your family?" },
    { id: 12, text: "Tell me about your friends." },
    { id: 13, text: "What sport do you like in your country?" },
    { id: 14, text: "Please, tell me about your favorite film?" },
    { id: 15, text: "Where did you go last night?" },
    { id: 16, text: "What do you like doing with your friend?" },
    { id: 17, text: "What sport do you like?" },
    { id: 18, text: "What did you do last night?" },
    { id: 19, text: "Tell me why you are interested in travel." },
    { id: 20, text: "Please describe your journey here today." },
    { id: 21, text: "Please tell me about a famous place in your country." },
    { id: 22, text: "Describe the room you are in?" },
    { id: 23, text: "Please tell me about yourself." },
    { id: 24, text: "What's your favorite book in your country?" },
    { id: 25, text: "What are you looking for in your new house?" },
    { id: 26, text: "What is a typical day like for you?" },
    { id: 27, text: "Why are you learning English?" },
    { id: 28, text: "Describe your job." },
    { id: 29, text: "Tell me the best way to travel around your country?" },
    { id: 30, text: "What is the food like in your country?" },
    { id: 31, text: "Describe a typical Vietnamese meal?" },
    { id: 32, text: "What is your favorite place?" },
    { id: 33, text: "When do you feel stressed or tired?" },
    { id: 34, text: "Please tell me about your first school?" },
    { id: 35, text: "What are you wearing today?" },
    { id: 36, text: "Tell me about the last time you talked with your mother." },
    { id: 37, text: "Please tell me about one of your good memories." },
];
